### ISSUE TITLE
[idea] Sonoff POW power as separate library

### ISSUE THREAD

**Issue by michalbogacz** [SensorsIot/Sonoff-POW#1]
Did you consider separating Sonoff_POW-master to its own project?
Separated library could be published to platform.io library registry (http://platformio.org/lib) and then included in projects as a dependency. An example of including libs as dependencies https://github.com/michalbogacz/flower-irrigator/blob/master/platformio.ini . 

Benefits for users:
- no copy paste code
- possible version managing

**Comment by SensorsIot** [comment]
I did not use platform.io till now, so I have no experience. Maybe I will once in the future.
