### ISSUE TITLE
    Set Param ?

### ISSUE THREAD

**Issue by nkimlevn** [SensorsIot/Sonoff-POW#5]
Dear,
```
    this->power_param = {12.286,0};
    this->current_param = {14.818,0};
    this->voltage_param = {0.435,0};
```
I don't understand. how do caculator the parameter ?
Thanks!

**Comment by SensorsIot** [comment]
I would go with Tasmota. It should support this device: https://tasmota.github.io/docs/devices/Sonoff-Pow/
